#!/bin/bash
export PATH=/usr/local/go/bin:$PATH
export GOPATH=/data/go
export GOROOT=/usr/local/go

if test $# -eq 0; then
	/scripts/builder installer
else
	test -n "$SRC" && cd "${GOPATH}${SRC}"
	exec "$@"
fi