#!/bin/bash

# run a command with the specified uid:gid, after guaranteeing that the user exists in the container

die() {
	echo "$*" 1>&2
	exit 1
}

ugid=$(stat -c '%u:%g' $(pwd))

uid=${ugid%:*}
gid=${ugid#*:}

if ! getent group $gid 1>/dev/null 2>&1; then
	groupadd -g $gid tmpgroup || die "cannot create tmpgroup"
fi

if ! getent passwd $uid 1>/dev/null 2>&1; then
	useradd -d /home/tmpuser -m -u $uid -g $gid tmpuser || die "cannot tmpuser"
fi

HOME=/home/tmpuser exec sudo -u \#$uid -E "$@"
